#' Generate match events from match IDs
#'
#' get_events_from_matches returns event data from Impect's API from a vector of match IDs
#'
#' @param token API token generated by get_token
#' @param matchids A vector of matchids


get_events_from_matches = function(token, matchids){
  t = 0

  cl <- makeCluster(detectCores())
  registerDoParallel(cl)

  start = Sys.time()
  # loop for each match input
  matchEvents <- foreach(
    i = matchids,
    .packages = c("foreach", "dplyr", "httr", "jsonlite"),
    .combine = bind_rows,
    .multicombine = T,
    .errorhandling = 'remove',
    .export = c("get_events")
  ) %dopar% {
    get_events(token, i)
  }
  stopCluster(cl)
  print(Sys.time() - start)

  for (i in as.character(c(0:9))){
    matchEvents <- select(matchEvents, -contains(i))
  }

  matchEvents %>%
    mutate(
      across(-c(matchid,gameTime,squadId,squadName,playerId,playerName,position,actionType,action,result,bodyPart,packingZone,pitchPosition,lane,AttackingTeam,phase,receiver,rec_type,end_packingZone,end_pitchPosition,end_lane,duelType,duelLostPlayer,duelLostPlayerId),
             ~ as.numeric(.x))
    ) %>%
    select(matchid:duelLostPlayer, non_shot_xg = PACKING_XG, shot_xg = SHOT_XG, post_shot_xg = POSTSHOT_XG)
}
