#' Generate match events from a match ID
#'
#' get_events returns event data from Impect's API for a single match
#'
#' @param token API token generated by get_token
#' @param matchid A match id


get_events = function(token, matchID){
  t = 0
  # get KpiNames
  kpiList <- content(GET(url = paste("https://api.impect.com/v4/customerapi/kpis"), add_headers(Authorization = paste("Bearer", token, sep = " "))))

  kpiNames <- c(0:1500)
  for (i in 1:length(kpiList$data)) {
    kpiNames[[kpiList$data[[i]]$kpiId+1]] <- kpiList$data[[i]]$kpiName
  }

  # check if match is available
  test <- (GET(url = paste0("https://api.impect.com/v4/customerapi/matches/",matchID,"/events"), add_headers(Authorization = paste("Bearer", token, sep = " "))))
  if (test$status_code == 200) {
    eventData <- content(test)
  } else {
    # loop in case of reaching the request limit
    Sys.sleep(1)
    t <- t+1
    eventData <- content(GET(url = paste0("https://api.impect.com/v4/customerapi/matches/",matchID,"/events"), add_headers(Authorization = paste("Bearer", token, sep = " "))))
    print(paste(k,"/",length(matchids),"matches. status: ",eventData$status_code))
  }

  test <- (GET(url = paste0("https://api.impect.com/v4/customerapi/matches/",matchID), add_headers(Authorization = paste("Bearer", token, sep = " "))))
  if (test$status_code == 200) {
    matchDetails <- content(test)
  } else {
    # loop in case of reaching the request limit
    Sys.sleep(1)
    t <- t+1
    matchDetails <- content(GET(url = paste0("https://api.impect.com/v4/customerapi/matches/",matchID),
                                add_headers(Authorization = paste("Bearer", token, sep = " "))))
  }

  playerNames <- append(matchDetails$data$squadHome$players,matchDetails$data$squadAway$players)
  teamNames <- vector(mode='list', length = 2)
  teamNames[[1]]$squadId <- matchDetails$data$squadHome$squadId
  teamNames[[1]]$name <- matchDetails$data$squadHome$name
  teamNames[[2]]$squadId <- matchDetails$data$squadAway$squadId
  teamNames[[2]]$name <- matchDetails$data$squadAway$name

  events <- setNames(data.frame(matrix(ncol = 45, nrow = 0)),
                     c("eventNumber","gameTime","gameTimeInSec","duration","squadId","squadName","playerId","playerName","position","actionType","action","result","opponents","pressure","distanceToGoal","pxT_team","pxT_opp","bodyPart","X","Y","adjX","adjY","packingZone","pitchPosition","lane","AttackingTeam","phase","pass_distance","pass_angle","receiver","rec_type","end_X","end_Y","end_adjX","end_adjY","end_packingZone","end_pitchPosition","end_lane","shot_distance","shot_angle","shot_y","shot_z","duelType","duelLostPlayerId","duelLostPlayer"))
  kpis <- setNames(data.frame(matrix(0, ncol = 1501, nrow = length(eventData$data$events))), kpiNames)
  matchid <-  rep(eventData$data$matchId,length(eventData$data$events))

  for (i in 1:length(eventData$data$events)) {
    ifelse(is.null(eventData$data$events[[i]]$eventNumber),
           eventNumber <- NA,
           eventNumber <- eventData$data$events[[i]]$eventNumber)
    ifelse(is.null(eventData$data$events[[i]]$gameTime),
           gameTime <- NA,
           gameTime <- eventData$data$events[[i]]$gameTime)
    ifelse(is.null(eventData$data$events[[i]]$gameTimeInSec),
           gameTimeInSec <- NA,
           gameTimeInSec <- eventData$data$events[[i]]$gameTimeInSec)
    ifelse(is.null(eventData$data$events[[i]]$periodId),
           periodId <- NA,
           periodId <- eventData$data$events[[i]]$periodId)
    ifelse(is.null(eventData$data$events[[i]]$duration),
           duration <- NA,
           duration <- eventData$data$events[[i]]$duration)
    ifelse(is.null(eventData$data$events[[i]]$squadId),
           squadId <- NA,
           squadId <- eventData$data$events[[i]]$squadId)
    ifelse(is.null(eventData$data$events[[i]]$player$id),
           playerId <- NA,
           playerId <- eventData$data$events[[i]]$player$id)
    ifelse(is.null(eventData$data$events[[i]]$opponents),
           opponents <- NA,
           opponents <- eventData$data$events[[i]]$opponents)
    ifelse(is.null(eventData$data$events[[i]]$pressure),
           pressure <- NA,
           pressure <- eventData$data$events[[i]]$pressure)
    ifelse(is.null(eventData$data$events[[i]]$start$coordinates$x),
           X <- NA,
           X <- eventData$data$events[[i]]$start$coordinates$x)
    ifelse(is.null(eventData$data$events[[i]]$start$coordinates$y),
           Y <- NA,
           Y <- eventData$data$events[[i]]$start$coordinates$y)
    ifelse(is.null(eventData$data$events[[i]]$start$adjCoordinates$x),
           adjX <- NA,
           adjX <- eventData$data$events[[i]]$start$adjCoordinates$x)
    ifelse(is.null(eventData$data$events[[i]]$start$adjCoordinates$y),
           adjY <- NA,
           adjY <- eventData$data$events[[i]]$start$adjCoordinates$y)
    ifelse(is.null(eventData$data$events[[i]]$start$packingZone),
           packingZone <- NA,
           packingZone <- eventData$data$events[[i]]$start$packingZone)
    ifelse(is.null(eventData$data$events[[i]]$start$pitchPosition),
           pitchPosition <- NA,
           pitchPosition <- eventData$data$events[[i]]$start$pitchPosition)
    ifelse(is.null(eventData$data$events[[i]]$start$lane),
           lane <- NA,
           lane <- eventData$data$events[[i]]$start$lane)
    ifelse(is.null(eventData$data$events[[i]]$end),
           end_X <- NA,
           end_X <- eventData$data$events[[i]]$end$coordinates$x)
    ifelse(is.null(eventData$data$events[[i]]$end),
           end_Y <- NA,
           end_Y <- eventData$data$events[[i]]$end$coordinates$y)
    ifelse(is.null(eventData$data$events[[i]]$end),
           end_adjX <- NA,
           end_adjX <- eventData$data$events[[i]]$end$adjCoordinates$x)
    ifelse(is.null(eventData$data$events[[i]]$end),
           end_adjY <- NA,
           end_adjY <- eventData$data$events[[i]]$end$adjCoordinates$y)
    ifelse(is.null(eventData$data$events[[i]]$end),
           end_packingZone <- NA,
           end_packingZone <- eventData$data$events[[i]]$end$packingZone)
    ifelse(is.null(eventData$data$events[[i]]$end),
           end_pitchPosition <- NA,
           end_pitchPosition <- eventData$data$events[[i]]$end$pitchPosition)
    ifelse(is.null(eventData$data$events[[i]]$end),
           end_lane <- NA,
           end_lane <- eventData$data$events[[i]]$end$lane)
    ifelse(is.null(eventData$data$events[[i]]$action),
           action <- NA,
           action <- eventData$data$events[[i]]$action)
    ifelse(is.null(eventData$data$events[[i]]$phase),
           phase <- NA,
           phase <- eventData$data$events[[i]]$phase)
    ifelse(is.null(eventData$data$events[[i]]$shot$distance),
           shot_distance <- NA,
           shot_distance <- eventData$data$events[[i]]$shot$distance)
    ifelse(is.null(eventData$data$events[[i]]$shot$targetPoint),
           shot_y <- NA,
           shot_y <- eventData$data$events[[i]]$shot$targetPoint$y)
    ifelse(is.null(eventData$data$events[[i]]$shot$targetPoint),
           shot_z <- NA,
           shot_z <- eventData$data$events[[i]]$shot$targetPoint$z)
    ifelse(is.null(eventData$data$events[[i]]$shot$angle),
           shot_angle <- NA,
           shot_angle <- eventData$data$events[[i]]$shot$angle)
    ifelse(is.null(eventData$data$events[[i]]$pass$distance),
           pass_distance <- NA,
           pass_distance <- eventData$data$events[[i]]$pass$distance)
    ifelse(is.null(eventData$data$events[[i]]$pass$angle),
           pass_angle <- NA,
           pass_angle <- eventData$data$events[[i]]$pass$angle)
    ifelse(is.null(eventData$data$events[[i]]$pass$receiver$playerId),
           receiverId <- NA,
           receiverId <- eventData$data$events[[i]]$pass$receiver$playerId)
    ifelse(is.null(eventData$data$events[[i]]$pass$receiver$type),
           rec_type <- NA,
           rec_type <- eventData$data$events[[i]]$pass$receiver$type)
    ifelse(is.null(eventData$data$events[[i]]$duel),
           duelType <- NA,
           duelType <- eventData$data$events[[i]]$duel$duelType)
    ifelse(is.null(eventData$data$events[[i]]$duel),
           duelLostPlayerId <- NA,
           duelLostPlayerId <- eventData$data$events[[i]]$duel$playerId)
    ifelse(is.null(eventData$data$events[[i]]$bodyPart),
           bodyPart <- NA,
           bodyPart <- eventData$data$events[[i]]$bodyPart)
    ifelse(is.null(eventData$data$events[[i]]$currentAttackingSquadId),
           Attacking <- NA,
           Attacking <- eventData$data$events[[i]]$currentAttackingSquadId)
    ifelse(is.null(eventData$data$events[[i]]$player$position$detailedPosition),
           position <- NA,
           position <- eventData$data$events[[i]]$player$position$detailedPosition)
    ifelse(is.null(eventData$data$events[[i]]$distanceToGoal),
           distanceToGoal <- NA,
           distanceToGoal <- eventData$data$events[[i]]$distanceToGoal)
    ifelse(is.null(eventData$data$events[[i]]$actionType),
           actionType <- NA,
           actionType <- eventData$data$events[[i]]$actionType)
    ifelse(is.null(eventData$data$events[[i]]$result),
           result <- NA,
           result <- eventData$data$events[[i]]$result)
    ifelse(is.null(eventData$data$events[[i]]$pxT$team),
           pxT_team <- NA,
           pxT_team <- eventData$data$events[[i]]$pxT$team)
    ifelse(is.null(eventData$data$events[[i]]$pxT$opp),
           pxT_opp <- NA,
           pxT_opp <- eventData$data$events[[i]]$pxT$opp)

    receiver <- NA
    AttackingTeam <- NA
    duelLostPlayer <- NA
    squadName <- NA
    playerName <- NA
    if (!is.na(pass_distance)) {
      if (pass_distance == 0) {
        pass_distance <- NA
      }
    }
    for (p in 1:length(playerNames)) {
      if (!is.na(playerId)) {
        if (playerId == playerNames[[p]]$playerId) {
          playerName <- playerNames[[p]]$commonname
        }
      }
      if (!is.na(duelLostPlayerId)) {
        if (duelLostPlayerId == playerNames[[p]]$playerId) {
          duelLostPlayer <- playerNames[[p]]$commonname
        }
      }
      if (!is.na(receiverId)) {
        if (receiverId == playerNames[[p]]$playerId) {
          receiver <- playerNames[[p]]$commonname
        }
      }
    }
    for (t in 1:2) {
      if (!is.na(squadId)) {
        if (squadId == teamNames[[t]]$squadId) {
          squadName <- teamNames[[t]]$name
        }
      }
      if (!is.na(Attacking)) {
        if (Attacking == teamNames[[t]]$squadId) {
          AttackingTeam <- teamNames[[t]]$name
        }
      }
    }

    if (length(eventData$data$events[[i]]$scorings) != 0) {
      for (j in 1:length(eventData$data$events[[i]]$scorings)) {
        kpis[i,eventData$data$events[[i]]$scorings[[j]]$kpiId+1] <- eventData$data$events[[i]]$scorings[[j]]$value + kpis[i,eventData$data$events[[i]]$scorings[[j]]$kpiId+1]
      }
    }
    eventdetails <- data.frame(eventNumber,periodId,gameTime,gameTimeInSec,duration,squadId,squadName,playerId,playerName,position,actionType,action,result,opponents,pressure,distanceToGoal,pxT_team,pxT_opp,bodyPart,X,Y,adjX,adjY,packingZone,pitchPosition,lane,AttackingTeam,phase,pass_distance,pass_angle,receiver,rec_type,end_X,end_Y,end_adjX, end_adjY,end_packingZone,end_pitchPosition,end_lane,shot_distance,shot_angle,shot_y,shot_z,duelType,duelLostPlayerId,duelLostPlayer)
    events <- rbind(events,eventdetails)
  }
  kpis[is.na(kpis)] <- 0
  matchEvents <- cbind(matchid,events,kpis)

  for (i in as.character(c(0:9))){
    matchEvents <- select(matchEvents, -contains(i))
  }

  matchEvents
}
