#' Generate match events from match IDs
#'
#' get_events_from_comps returns event data from Impect's API from a vector of competition IDs. This is quicker for a single competition than using get_matches and then get_events_from_matches.
#'
#' @param token API token generated by get_token
#' @param compids A vector of compids

get_events_from_comps = function(token, compids){
  t = 0
  matchEvents <- data.frame()

  for(l in 1:length(compids)){
    comp = compids[l]

    compIteration <- content(
      GET(url = paste0("https://api.impect.com/v4/customerapi/scouting/competitionIterations/",comp), add_headers(Authorization = paste("Bearer", token, sep = " ")))
    )

    matchids = c()
    for (i in 1:length(compIteration$data$competitionIterationSteps)) {
      for (j in 1:length(compIteration$data$competitionIterationSteps[[i]]$matches)) {
        if (!is.null(compIteration$data$competitionIterationSteps[[i]]$matches[[j]]$squadHome$goals)) {
          matchids <- append(matchids,compIteration$data$competitionIterationSteps[[i]]$matches[[j]]$matchId)
        }
      }
    }

    # get KpiNames
    kpiList <- content(GET(url = paste("https://api.impect.com/v4/customerapi/kpis"), add_headers(Authorization = paste("Bearer", token, sep = " "))))

    kpiNames <- c(0:1500)
    for (i in 1:length(kpiList$data)) {
      kpiNames[[kpiList$data[[i]]$kpiId+1]] <- kpiList$data[[i]]$kpiName
    }

    # set up parallel
    cl <- makeCluster(detectCores())
    registerDoParallel(cl)

    # loop for each match input
    temp_matches <- foreach(
      i = matchids,
      .combine = bind_rows,
      .multicombine = T,
      .errorhandling = 'remove',
      .export = c("get_events"),
      .packages = c("foreach", "dplyr", "httr", "jsonlite")
    ) %dopar% {
      get_events(token, i)
    }
    stopCluster(cl)

    matchEvents <- bind_rows(temp_matches, matchEvents)
  }

  for (i in as.character(c(0:9))){
    matchEvents <- select(matchEvents, -contains(i))
  }

  matchEvents %>%
    mutate(
      across(-c(matchid,gameTime,squadId,squadName,playerId,playerName,position,actionType,action,result,bodyPart,packingZone,pitchPosition,lane,AttackingTeam,phase,receiver,rec_type,end_packingZone,end_pitchPosition,end_lane,duelType,duelLostPlayer,duelLostPlayerId),
             ~ as.numeric(.x))
  ) %>%
  select(matchid:duelLostPlayer, non_shot_xg = PACKING_XG, shot_xg = SHOT_XG, post_shot_xg = POSTSHOT_XG)
}
