#' Generate match events from match IDs
#'
#' get_events_from_matches returns event data from Impect's API from a vector of match IDs
#'
#' @param token API token generated by get_token
#' @param matchids A vector of matchids


get_events_from_matches = function(token, matchids){
  t = 0
  # get KpiNames
  kpiList <- content(GET(url = paste("https://api.impect.com/v4/customerapi/kpis"), add_headers(Authorization = paste("Bearer", token, sep = " "))))

  kpiNames <- c(0:1500)
  for (i in 1:length(kpiList$data)) {
    kpiNames[[kpiList$data[[i]]$kpiId+1]] <- kpiList$data[[i]]$kpiName
  }

  cl <- makeCluster(detectCores())
  registerDoParallel(cl)

  # loop for each match input
  temp_matches <- foreach(
    i = matchids,
    .combine = bind_rows,
    .multicombine = T,
    .errorhandling = 'remove',
    .export = c("get_events"),
    .packages = c("foreach", "dplyr", "httr", "jsonlite")
  ) %dopar% {
    get_events(token, i)
  }
  stopCluster(cl)

  matchEvents <- bind_rows(temp_matches, matchEvents)

  for (i in as.character(c(0:9))){
    matchEvents <- select(matchEvents, -contains(i))
  }

  matchEvents %>%
    mutate(
      across(-c(matchid,gameTime,squadId,squadName,playerId,playerName,position,actionType,action,result,bodyPart,packingZone,pitchPosition,lane,AttackingTeam,phase,receiver,rec_type,end_packingZone,end_pitchPosition,end_lane,duelType,duelLostPlayer,duelLostPlayerId),
             ~ as.numeric(.x))
    ) %>%
    select(matchid:duelLostPlayer, non_shot_xg = PACKING_XG, shot_xg = SHOT_XG, post_shot_xg = POSTSHOT_XG)
}
