#' Get minutes played by all players in a single matches
#'
#' get_mins returns a df with all minutes played in a single game
#'
#' @param token API token generated by get_token
#' @param matchID A single match ID

get_mins = function(token, matchID){
  t = 0

  test <- (GET(url = paste0("https://api.impect.com/v4/customerapi/matches/",matchID), add_headers(Authorization = paste("Bearer", token, sep = " "))))
  if (test$status_code==200) {
    matchDetails <- content(test)
  } else {
    # loop in case of reaching the request limit
    Sys.sleep(1)
    t <- t+1
    matchDetails <- (GET(url = paste0("https://api.impect.com/v4/customerapi/matches/",matchID), add_headers(Authorization = paste("Bearer", token, sep = " "))))
    matchDetails <- content(matchDetails)
  }

  for (p in 1:length(matchDetails$data$squadHome$players)) {
    matchDetails$data$squadHome$players[[p]]$teamName <- matchDetails$data$squadHome$name
  }
  for (p in 1:length(matchDetails$data$squadAway$players)) {
    matchDetails$data$squadAway$players[[p]]$teamName <- matchDetails$data$squadAway$name
  }
  allDetails <- append(matchDetails$data$squadHome$players,matchDetails$data$squadAway$players)

  nplayers = length(allDetails)
  q <- 1
  for (p in 1:nplayers) {
    if (length(allDetails[[p]]$playTime) >= 2) {
      allDetails[[nplayers+q]] <- allDetails[[p]]
      allDetails[[nplayers+q]]$playTime[[1]] <- allDetails[[nplayers+q]]$playTime[[2]]
      q <- q + 1
    }
  }
  for (p in 1:nplayers) {
    if (length(allDetails[[p]]$playTime) >= 3) {
      if (allDetails[[p]]$playTime[[1]]$detailedPosition != allDetails[[p]]$playTime[[3]]$detailedPosition) {
        allDetails[[nplayers+q]] <- allDetails[[p]]
        allDetails[[nplayers+q]]$playTime[[1]] <- allDetails[[nplayers+q]]$playTime[[3]]
        q <- q + 1
      } else {
        allDetails[[p]]$playTime[[1]]$playDuration = allDetails[[p]]$playTime[[1]]$playDuration + allDetails[[p]]$playTime[[3]]$playDuration
        allDetails[[p]]$playTime[[1]]$matchSahre = allDetails[[p]]$playTime[[1]]$matchSahre + allDetails[[p]]$playTime[[3]]$matchSahre
      }
    }
  }
  for (p in 1:nplayers) {
    if (length(allDetails[[p]]$playTime) >= 4) {
      if (allDetails[[p]]$playTime[[1]]$detailedPosition != allDetails[[p]]$playTime[[4]]$detailedPosition & allDetails[[p]]$playTime[[2]]$detailedPosition != allDetails[[p]]$playTime[[4]]$detailedPosition) {
        allDetails[[nplayers+q]] <- allDetails[[p]]
        allDetails[[nplayers+q]]$playTime[[1]] <- allDetails[[nplayers+q]]$playTime[[4]]
        q <- q + 1
      } else if (allDetails[[p]]$playTime[[1]]$detailedPosition == allDetails[[p]]$playTime[[4]]$detailedPosition) {
        allDetails[[p]]$playTime[[1]]$playDuration = allDetails[[p]]$playTime[[1]]$playDuration + allDetails[[p]]$playTime[[4]]$playDuration
        allDetails[[p]]$playTime[[1]]$matchSahre = allDetails[[p]]$playTime[[1]]$matchSahre + allDetails[[p]]$playTime[[4]]$matchSahre
      } else if (allDetails[[p]]$playTime[[2]]$detailedPosition == allDetails[[p]]$playTime[[4]]$detailedPosition) {
        allDetails[[p]]$playTime[[2]]$playDuration = allDetails[[p]]$playTime[[2]]$playDuration + allDetails[[p]]$playTime[[4]]$playDuration
        allDetails[[p]]$playTime[[2]]$matchSahre = allDetails[[p]]$playTime[[2]]$matchSahre + allDetails[[p]]$playTime[[4]]$matchSahre
      }
    }
  }

  matchid <-  rep(matchDetails$data$matchId,length(allDetails))
  minsPlayed <- setNames(data.frame(matrix(ncol = 11, nrow = 0)), c("playerId","teamName", "commonname","birthdate","birthplace","country","leg","matchShare","playDuration","position","detailedPosition"))

  for (i in 1:length(allDetails)) {
    ifelse(is.null(allDetails[[i]]$playerId),playerId<-NA,playerId <- allDetails[[i]]$playerId)
    ifelse(is.null(allDetails[[i]]$teamName),teamName<-NA,teamName <- allDetails[[i]]$teamName)
    ifelse(is.null(allDetails[[i]]$commonname),commonname<-NA,commonname <- allDetails[[i]]$commonname)
    ifelse(is.null(allDetails[[i]]$birthdate),birthdate<-NA,birthdate <- allDetails[[i]]$birthdate)
    ifelse(is.null(allDetails[[i]]$birthplace),birthplace<-NA,birthplace <- allDetails[[i]]$birthplace)
    ifelse(length(allDetails[[i]]$countries)==0,country<-NA,country <- allDetails[[i]]$countries[[1]]$name)
    ifelse(is.null(allDetails[[i]]$leg),leg<-NA,leg<-allDetails[[i]]$leg)
    ifelse(length(allDetails[[i]]$playTime)==0,matchShare<-NA,matchShare<-allDetails[[i]]$playTime[[1]]$matchShare)
    ifelse(length(allDetails[[i]]$playTime)==0,playDuration<-NA,playDuration<-allDetails[[i]]$playTime[[1]]$playDuration)
    ifelse(length(allDetails[[i]]$playTime)==0,position<-NA,position<-allDetails[[i]]$playTime[[1]]$position)
    ifelse(length(allDetails[[i]]$playTime)==0,detailedPosition<-NA,detailedPosition<-allDetails[[i]]$playTime[[1]]$detailedPosition)
    if (!is.na(playDuration)) {
      if (playDuration == matchShare) {
        matchShare <- 0
      }
    }
    playermins <- data.frame(playerId,teamName,commonname,birthdate,birthplace,country,leg,matchShare,playDuration,position,detailedPosition)
    minsPlayed <- rbind(minsPlayed,playermins)
  }

  cbind(matchid,minsPlayed)
}
