#' Get minutes played by all players in selected competitions
#'
#' get_mins_from_matches returns a df with all minutes played in a vector of comp IDs, which can be generated with get_competition
#'
#' @param token API token generated by get_token
#' @param compids A vector of competition IDs

get_mins_from_matches = function(token, matchID){
  t = 0
  minsPlayed <- data.frame()

  for(l in 1:length(compids)){
    comp = compids[l]

    compIteration <- content(
      GET(url = paste0("https://api.impect.com/v4/customerapi/scouting/competitionIterations/",comp), add_headers(Authorization = paste("Bearer", token, sep = " ")))
    )

    matchids = c()
    for (i in 1:length(compIteration$data$competitionIterationSteps)) {
      for (j in 1:length(compIteration$data$competitionIterationSteps[[i]]$matches)) {
        if (!is.null(compIteration$data$competitionIterationSteps[[i]]$matches[[j]]$squadHome$goals)) {
          matchids <- append(matchids,compIteration$data$competitionIterationSteps[[i]]$matches[[j]]$matchId)
        }
      }
    }

    # set up parallel
    cl <- makeCluster(detectCores())
    registerDoParallel(cl)

    start = Sys.time()
    # loop for each match input
    temp_matches <- foreach(
      i = matchids,
      .combine = bind_rows,
      .multicombine = T,
      .errorhandling = 'remove',
      .export = c("get_mins"),
      .packages = c("foreach", "dplyr", "httr", "jsonlite")
    ) %dopar% {
      get_mins(token, i)
    }
    stopCluster(cl)
    print(Sys.time() - start)

    minsPlayed <- bind_rows(temp_matches, minsPlayed)
  }

  minsPlayed
}
