#' Generate match information
#'
#' get_matches returns information from Impect's API about match details - including match_id, match_date, home + away teams and final score.
#'
#' @param token API token generated by get_token
#' @param comp Impect competition ID

get_matches = function(token, comp){
  t = 0
  compIteration <- content(
    GET(url = paste0("https://api.impect.com/v4/customerapi/scouting/competitionIterations/",comp),
        add_headers(Authorization = paste("Bearer", token, sep = " ")))
  )

  matchids = c()
  for (i in 1:length(compIteration$data$competitionIterationSteps)) {
    for (j in 1:length(compIteration$data$competitionIterationSteps[[i]]$matches)) {
      if (!is.null(compIteration$data$competitionIterationSteps[[i]]$matches[[j]]$squadHome$goals)) {
        matchids <- append(matchids,compIteration$data$competitionIterationSteps[[i]]$matches[[j]]$matchId)
      }
    }
  }

  # set up parallel
  cl <- makeCluster(detectCores())
  registerDoParallel(cl)

  start = Sys.time()
  matches = foreach(
    i = matchids,
    .combine = bind_rows,
    .multicombine = T,
    .errorhandling = 'remove',
    .export = c("get_match_details"),
    .packages = c("foreach", "dplyr", "httr", "jsonlite")
  ) %dopar% {
    get_match_details(token, i)
  }
  stopCluster(cl)
  print(Sys.time() - start)

  matches
}
