#' Generate competition information
#'
#' get_competitons returns information from Impect's API including competition ID + name and season ID + name
#'
#' @param token API token generated by get_token

get_competitions = function(token){
  compids <- content(GET(url = "https://api.impect.com/v3/customerapi/scouting/competitionIterations", add_headers(Authorization = paste("Bearer", token, sep = " "))))

  competitions <- data.frame(matrix(unlist(compids$data), nrow = length(compids$data), byrow=TRUE))

  colnames(competitions) <- c("competitionIterationId","competition","competitionId","season","countryId","country")
  competitions
}
